Split certificate renewal into setting and renewing sections
mesosphere/dcos-docs-site pull request #3297
Opened 2020-10-23 17:21 UTC by jongiddy

## Jira Ticket
https://jira.d2iq.com/browse/D2IQ-71896

## Description of changes being made

## Checklist
- [x] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [x] Test all commands and procedures, if applicable.
- [x] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2020-10-23 18:23 UTC, vinodkone approved these changes
LGTM

2020-10-26 21:19 UTC, cmastr approved these changes

2020-10-26 21:58 UTC, cneth requested changes
Looks good, just one minor comment.

2020-10-26 21:58 UTC, cneth commented on pages/mesosphere/dcos/2.2/security/ent/tls-ssl/ca-custom/index.md
> +To replace the CA certificate (for example, if it is expiring or compromised), perform the following procedure consisting of three patch upgrades.  This procedure ensures that the cluster stays healt
The first time I read this, I breezed over the 'three patch' part.  Repetition seems good here:

```suggestion
To replace the CA certificate (for example, if it is expiring or compromised), perform the following procedure consisting of three patch upgrades.  Three patch upgrades are required to ensure that the cluster stays healthy during the certificate replacement.  If Calico is enabled (the default setting), then workloads may be stopped.
```

2020-10-27 15:58 UTC, merged