D2IQ-72532: update quota docs, add limit range info
mesosphere/dcos-docs-site pull request #3313
Opened 2020-10-29 21:35 UTC by natmegs

Closes D2IQ-72532

## Jira Ticket
 
https://jira.d2iq.com/browse/D2IQ-72532 

## Description of changes being made

This ticket documents new project limit range features and updates the affected quota docs. This feature was originally not slated to be in the 1.2 release but with the extended deadline the UI has been updated to latest.

## Checklist
- [x] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [x] Create your PR against `staging`, not `master`. 
- [x] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2020-10-29 22:50 UTC, cneth requested changes

2020-10-29 22:50 UTC, cneth commented on pages/ksphere/kommander/1.2/projects/project-quotas-limit-range/index.md
> +Kommander provides a set of default resources you can set Quotas for, or you can define Quotas for custom resources. It is recommended to set Quotas for CPU and Memory. Using Limit Ranges you can res
```suggestion
Kommander provides a set of default resources you can set Quotas for, or you can define Quotas for custom resources. It is recommended to set Quotas for CPU and Memory. Using Limit Ranges, you can restrict the resource consumption of individual Pods, Containers, and Persistent Volume Claims in the project namespace. You can also constrain memory and CPU resources consumed by Pods and Containers, and you can constrain storage resources consumed by Persistent Volume Claims.
```

2020-10-29 22:50 UTC, cneth commented on pages/ksphere/kommander/1.2/projects/project-quotas-limit-range/index.md
> +All the Project Quotas are defined using a Kubernetes FederatedResourceQuota called kommander and can also be created/updated using kubectl:
```suggestion
All the Project Quotas are defined using a Kubernetes FederatedResourceQuota called kommander which can also be created/updated using kubectl:
```

2020-10-29 22:50 UTC, cneth commented on pages/ksphere/kommander/1.2/projects/project-quotas-limit-range/index.md
> +Then, if you run the following command on a Kubernetes cluster associated with the Project, you’ll see a Kubernetes Secret Object, in the corresponding namespace:
```suggestion
Then, if you run the following command on a Kubernetes cluster associated with the Project, you’ll see a Kubernetes Secret Object in the corresponding namespace:
```

2020-10-30 18:26 UTC, cmastr approved these changes

2020-10-30 18:29 UTC, merged