adding warnings to release notes
mesosphere/dcos-docs-site pull request #3319
Opened 2020-11-03 18:31 UTC by cmastr

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

## Description of changes being made

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2020-11-05 17:59 UTC, vinodkone requested changes

2020-11-05 17:59 UTC, vinodkone commented on pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
> +WARNING: The DC/OS 2.2 release includes an issue that changes the name of the 'libnetwork' certificate which causes its bootstrap to restart Docker and workloads, if you upgrade from 2.1.x. Because o
DC/OS 2.2.0

2020-11-05 17:59 UTC, vinodkone commented on pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
> +WARNING: The DC/OS 2.2 release includes an issue that changes the name of the 'libnetwork' certificate which causes its bootstrap to restart Docker and workloads, if you upgrade from 2.1.x. Because o
DC/OS 2.2.0

2020-11-05 17:59 UTC, vinodkone commented on pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
>  Mesosphere&reg; DC/OS&trade; 2.2 was released on 29, October 2020.
DC/OS 2.2.0

2020-11-05 17:59 UTC, vinodkone commented on pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
> +WARNING: The DC/OS 2.2 release includes an issue that changes the name of the 'libnetwork' certificate which causes its bootstrap to restart Docker and workloads, if you upgrade from 2.1.x. Because o
DC/OS 2.2.0

2020-11-05 17:59 UTC, vinodkone commented on pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
>  Mesosphere&reg; DC/OS&trade; 2.2 was released on 29, October 2020.
DC/OS 2.2.0 in "title", "navigationTitle", "excerpt:" as well

2020-11-05 20:50 UTC, orsenthil approved these changes
LGTM.

2020-11-05 21:06 UTC, cmastr commented
Must add DCOS 2.2.1 release notes.

2020-11-06 18:37 UTC, vinodkone approved these changes

2020-11-06 19:45 UTC, cneth approved these changes
LGTM

2020-11-06 20:21 UTC, closed without merging

2020-11-06 20:28 UTC, cmastr commented
closing in favor of #3325