Jcb/d2iq 72843
mesosphere/dcos-docs-site pull request #3320
Opened 2020-11-03 20:21 UTC by JohnB64-JBV

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

https://jira.d2iq.com/browse/D2IQ-72843 

Added Breaking Changes to Release Notes for 2.1.0, 2.1.1, and 2.2, and a short paragraph to the page, "Using a Private Docker Registry" in those versions, as a response to handling the new Docker Hub image pull rate limiting change

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2020-11-03 20:45 UTC, cneth requested changes

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
> +    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) command
Nit, this is an option, not a 'command'. 

```suggestion
    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) option
```

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
> +    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) command
```suggestion
    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) option
```

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
> +    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) command
```suggestion
    - Use the [docker.forcePullImage](https://mesosphere.github.io/marathon/docs/native-docker.html#forcing-a-docker-pull) option
```

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
> +    1. Task-specific credentials using secrets: [Reference private dockcer registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/
```suggestion
    1. Task-specific credentials using secrets: [Reference private docker registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/#reference-private-docker-registry-credentials-in-dcos-secrets-enterprise)
```

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
> +    1. Task-specific credentials using secrets: [Reference private dockcer registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/
```suggestion
    1. Task-specific credentials using secrets: [Reference private docker registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/#reference-private-docker-registry-credentials-in-dcos-secrets-enterprise)
```

2020-11-03 20:45 UTC, cneth commented on pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
> +    1. Task-specific credentials using secrets: [Reference private dockcer registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/
```suggestion
    1. Task-specific credentials using secrets: [Reference private docker registry credentials in DC/OS secrets](https://docs.d2iq.com/mesosphere/dcos/2.1/deploying-services/private-docker-registry/#reference-private-docker-registry-credentials-in-dcos-secrets-enterprise)
```

2020-11-03 21:07 UTC, cmastr approved these changes

2020-11-04 07:04 UTC, fatz approved these changes
LGTM.

Shall we maybe rename this topic to something like "Docker Registry authentication" and have private docker registries as a subtitle of it?

2020-11-04 15:12 UTC, JohnB64-JBV commented
The Vale linter is what triggered the unsuccessful check, and the flagged item is OK.

2020-11-04 22:40 UTC, merged