[op docs] Remove konvoy download instructions from kommander docs
mesosphere/dcos-docs-site pull request #3404
Opened 2021-01-25 23:04 UTC by gracedo

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

https://jira.d2iq.com/browse/D2IQ-62854

## Description of changes being made
Looks like konvoy docs do not include specific details on download instructions, so we should remove them from kommander and just link to the konvoy docs.

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-01-26 15:15 UTC, cmastr commented
@gracedo this was done on purpose bc Chris Gaun requested. Why do we want to take it out now?

2021-01-26 15:16 UTC, cmastr requested changes

2021-01-26 15:16 UTC, cmastr commented on pages/dkp/kommander/1.3/install/index.md
>  # Download and Install
This needs some rewording.

2021-01-26 18:50 UTC, gracedo commented
> @gracedo this was done on purpose bc Chris Gaun requested. Why do we want to take it out now?

I wasn't aware of Chris's request. Do you know why he requested it be documented this way? Maybe Konvoy at the time had the same detailed instructions? I just find it strange to include these instructions when Konvoy instructs the user to check their email for the download how-to. @dkoshkin wdyt?

2021-01-26 22:13 UTC, cneth approved these changes

2021-01-27 22:32 UTC, cmastr commented
> > @gracedo this was done on purpose bc Chris Gaun requested. Why do we want to take it out now?
> 
> I wasn't aware of Chris's request. Do you know why he requested it be documented this way? Maybe Konvoy at the time had the same detailed instructions? I just find it strange to include these instructions when Konvoy instructs the user to check their email for the download how-to. @dkoshkin wdyt?

yeah, sorry I was a little hasty. I think you're right that this used to work differently and maybe doesn't need to be this way anymore. Let's get another opinion though. Will wait for Dimitri.

2021-01-27 22:37 UTC, dkoshkin approved these changes

2021-01-27 23:42 UTC, gracedo commented
@cmastr I synced with @dkoshkin and he agrees that we should remove these instructions from kommander docs and link to konvoy download docs

2021-01-28 16:16 UTC, cmastr commented
Ok, good to go then. Thanks Grace!

2021-01-28 16:16 UTC, cmastr approved these changes

2021-01-28 16:17 UTC, merged