[Doc][Kommander] Kommander 1.2.1 Release Notes for Patch.
mesosphere/dcos-docs-site pull request #3477
Opened 2021-03-11 16:57 UTC by russurquhart1

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

## Description of changes being made
Release Notes for Kommander 1.2.1 Patch

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `main`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +In Kommander 1.3, all new projects were created with a default NetworkPolicy that only allowed traffic originating within your Projects namespace. This policy was also created in all existing project
```suggestion
```

This is a 1.3 specific feature so we can remove all this

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +The result of this default policy was that Pods could not talk to Pods outside of that namespace. In some cases this was not a desired default state. As of Kommander 1.3.1, no default NetworkPolicy i
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +If you are upgrading from Kommander 1.3 and already made the necessary changes to address this issue (for example, by adding a NetworkPolicy with the desired traffic rules), then upgrading to Kommand
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Add license delete mutation.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Replace license table with single license detail view.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Allow workspace namespace to be configurable.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Fix empty non-Konvoy cluster Platform Services tab.
```suggestion
- Fix empty non-Konvoy cluster Platform Services tab.
```
```suggestion
- Bump kubecost to fix an issue that occasionally caused pods to fail to deploy.
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Disable all platform services when Foundational Components are disabled in the UI.
```suggestion
- Fix bug in Kommander UI where LDAP Root CA is malformed when saved.
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- All federated platform services are now successfully removed when the kubeaddons controller is disabled.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- When self attaching a kommander cluster, the dex-k8s-authenticator configmap is no longer updated as this causes invalid links on the generate token page.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Kubecost: Ensure kubectl deletes do not fail if resource is already deleted.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Fixes bug in Kommander UI where LDAP Root CA is not correct when saved.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Updates UI to only ship with needed dependencies.
```suggestion
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Addon: 1.3.1-5
```suggestion
- Addon: 1.2.1-2
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Chart: 0.15.3
```suggestion
- Chart: 0.12.19
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- kommander-federation (yakcl): 0.8.8
```suggestion
- kommander-federation (yakcl): 0.6.10
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- kommander-licensing (yakcl): 0.8.8
```suggestion
- kommander-licensing (yakcl): 0.6.10
```

2021-03-11 17:07 UTC, gracedo commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- UI: 6.91.1
```suggestion
- UI: 6.55.2
```

2021-03-11 19:08 UTC, cneth requested changes

2021-03-11 19:08 UTC, cneth commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +- Fix bug in Kommander UI where LDAP Root CA is malformed when saved.
```suggestion
- Fix bug in Kommander UI where LDAP Root CA is malformed when saved. (COPS-6884)
```

2021-03-11 19:08 UTC, cneth commented on pages/dkp/kommander/1.2/version-policy/index.md
> +For example, Kommander 1.3.0 supports:
```suggestion
For example, Kommander 1.2.0 supports:
```

2021-03-11 19:08 UTC, cneth commented on pages/dkp/kommander/1.2/version-policy/index.md
> +- You cannot deploy Kommander 1.1.x on Konvoy 1.6.x
This mentions Kommander 1.3 but this is a 1.2 page.

```suggestion
Konvoy and Kommander release `MAJOR.MINOR` versions together and are compatible with each other for that version set. This means, Kommander 1.2, and all of its patch versions (e.g. 1.2.0, 1.2.1), can deploy successfully on any version of Konvoy 1.6. Mixing minor versions is prohibited and the following is not supported:

- You cannot deploy Kommander 1.2.x on Konvoy 1.7.x
- You cannot deploy Kommander 1.1.x on Konvoy 1.6.x
```

2021-03-11 19:20 UTC, cneth commented on pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
> +| **Default**        | 1.18.10  |
This table confuses me...  Kommander doesn't install Kubernetes.  The 'Default values' here don't match what is in the Konvoy 1.6.2 rn.

2021-03-12 17:04 UTC, cneth approved these changes

2021-03-12 18:04 UTC, merged