[Doc][Kommander] Added updated Release Notes info for 1.4 beta 1.
mesosphere/dcos-docs-site pull request #3483
Opened 2021-03-11 20:38 UTC by russurquhart1

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

## Description of changes being made
Added updated Release Notes info for 1.4 beta 1.

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `main`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-03-11 20:45 UTC, gracedo approved these changes

2021-03-11 20:45 UTC, gracedo commented on pages/dkp/kommander/1.4/release-notes/index.md
>  - Addon: 1.4.0-1
```suggestion
- Addon: 1.4.0-6
```

2021-03-11 20:45 UTC, gracedo commented on pages/dkp/kommander/1.4/release-notes/index.md
>  - Chart: 0.16.1
```suggestion
- Chart: 0.19.0
```

2021-03-11 20:45 UTC, gracedo commented on pages/dkp/kommander/1.4/release-notes/index.md
> +- UI: 6.91.0
```suggestion
- UI: 6.91.1
```

2021-03-12 19:57 UTC, cmastr approved these changes

2021-03-12 20:13 UTC, cneth requested changes

2021-03-12 20:13 UTC, cneth commented on pages/dkp/kommander/1.4/version-policy/index.md
> +## Supported Kubernetes versions
I think we decided to remove this table from Kommander releases, right?

2021-03-12 20:13 UTC, cneth commented on pages/dkp/kommander/1.4/release-notes/index.md
>  # Supported Versions
We decided to remove this table from Kommander RN, right?  It's just too confusing because Konvoy also has a table and they get out of sync.

2021-03-12 20:44 UTC, cneth approved these changes

2021-03-12 21:48 UTC, merged