Add KUDO Cassandra Platform Service Docs
mesosphere/dcos-docs-site pull request #3515
Opened 2021-04-06 06:41 UTC by kaiwalyajoshi

## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

[D2IQ-74567](https://jira.d2iq.com/browse/D2IQ-74567)

## Description of changes being made

- Rearrange sections of Project->Platform Services to have sub-sections for Helm and KUDO based services.
- Add subsection for Platform Services Catalog.
- Add KUDO Cassandra Subsection.

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-04-06 06:51 UTC, kaiwalyajoshi commented
Run the following to see the docs:
1. `gh repo clone mesosphere/dcos-docs-site`
1. `git checkout kjoshi/kommander-platform-services-catalog`
1. `make clean`
1. `npm install`
1. `npm run dev`
1. Navigate to http://0.0.0.0:3000/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/

2021-04-06 21:35 UTC, russurquhart1 approved these changes

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/federated-addons/index.md
> +Ensure the projectns variable is set before executing the command. This variable is the project namespace (i.e. Kubernetes Namespace associated with the project) that was defined/created when the pro
```suggestion
Ensure the projectns variable is set before executing the command. This variable is the project namespace (that is, the Kubernetes Namespace associated with the project) that was defined/created when the project itself was initially created.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/federated-addons/index.md
> +Then, if you run the following command on a Kubernetes cluster associated with the Project, you’ll see a Kubernetes Addon Object, in the corresponding namespace:
```suggestion
After you run the following command on a Kubernetes cluster associated with the Project, a Kubernetes Addon Object appears in the corresponding namespace:
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +- KUDO will then install Cassandra in the Project namespace created via Kommander.
```suggestion
- KUDO will then install Cassandra in the Project namespace created using Kommander.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +At this point its useful to have an understanding of [KUDO Operator Plans](https://kudo.dev/docs/what-is-kudo.html#operator-plans) and the [KUDO CLI](https://kudo.dev/docs/cli/installation.html) shou
```suggestion
At this point it is useful to have an understanding of [KUDO Operator Plans](https://kudo.dev/docs/what-is-kudo.html#operator-plans) and the [KUDO CLI](https://kudo.dev/docs/cli/installation.html) should be installed.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +If any issues are encountered during the above, the [Troubleshooting](#Troubleshooting) section has guidance.
```suggestion
If any issues are encountered during the above, refer to the [Troubleshooting](#Troubleshooting) section.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +The current set of parameters set can be reterived using the kubectl command with the two additional tools:
```suggestion
The current parameters set can be reterived using the kubectl command with the two additional tools:
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +Parameters can be updated via arguements to the KUDO CLI.
```suggestion
Parameters can be updated using arguments to the KUDO CLI.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +- Increase the number of nodes via the KUDO CLI:
```suggestion
- Increase the number of nodes using the KUDO CLI:
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +To update multiple paramters at once, its recommended to submit the updated parameters via the KUDO CLI.
```suggestion
To update multiple parameters at once, it is recommended to submit the updated parameters using the KUDO CLI.
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +Apply the desired updates in `cassandra-params.yml` via the KUDO CLI:
```suggestion
Apply the desired updates in `cassandra-params.yml` using the KUDO CLI:
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +Grafana dashboards can be [imported](https://grafana.com/docs/grafana/latest/dashboards/export-import/) or recurring dashboards can be defined inline for Kommander to import via [adding custom dashbo
```suggestion
Grafana dashboards can be [imported](https://grafana.com/docs/grafana/latest/dashboards/export-import/) or recurring dashboards can be defined inline for Kommander to import through [adding custom dashboards](/dkp/kommander/1.3/centralized-monitoring/#adding-custom-dashboards). 
```

2021-04-06 21:35 UTC, russurquhart1 commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +To monitor all the events occurring in the namespace, its helpful to look at event log via:
```suggestion
To monitor all the events occurring in the namespace, its helpful to look at event log:
```

2021-04-07 12:16 UTC, rishabh96b approved these changes

2021-04-07 12:16 UTC, rishabh96b commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +Kommander Catalog adds integration for [KUDO Cassandra Operator](https://github.com/kudobuilder/operators/tree/master/repository/cassandra/3.11), which simplifies day 2 operations of [Apache Cassandr
```suggestion
Kommander Catalog adds integration for [KUDO Cassandra Operator](https://github.com/mesosphere/kudo-cassandra-operator/), which simplifies day 2 operations of [Apache Cassandra](https://cassandra.apache.org/). 
```

2021-04-12 17:13 UTC, cneth requested changes

2021-04-12 17:13 UTC, cneth commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +```
At first glance, it is not at all clear what `operator version 1.0.2` has to do with Cassandra `v3.11.7-1`.  I understand it _after_ reading the Cassandra operator docs page (which has a table), should there be a reference to that table here?  Also, in that table,
the versions are listed as `3.11.7-1.0.2` but here you have `v3.11.7-1`.  Which is correct?

Here's my suggested fix for these:  

```suggestion
**Example** Upgrade KUDO Cassandra from `v3.11.6-1.0.1` to `v3.11.7-1.0.2`:
When upgrading, you should understand the mapping between Cassandra versions and operator versions.   For more information, see the table at the end of the [Cassandra operator](https://github.com/mesosphere/kudo-cassandra-operator/tree/master/docs)
```
kubectl kudo upgrade cassandra -n test-project-zc6tc --instance cassandra --operator-version 1.0.2 
```
```

2021-04-12 17:13 UTC, cneth commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +The KUDO Cassandra operator supports creation of a service that opens up ports to access Cassandra from outside the cluster. To enable this, you have to set the following variables:
```suggestion
The KUDO Cassandra operator supports creation of a service that opens up ports to access Cassandra from outside the cluster. To enable this, you have to set one or more of the following variables:
```

2021-04-12 17:13 UTC, cneth commented on pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-cassandra/index.md
> +Once the update plan is complete, we can delete the PVC that was attached to the KUDO Cassandra pod/cassandra-node-3. Not deleting or cleaning the PVC will result in issues when scaling the cluster u
```suggestion
Once the update plan is complete, you should delete (or clean) the PVC that was attached to the KUDO Cassandra pod/cassandra-node-3. Failing to delete or clean the PVC will result in issues when scaling the cluster up next time.
```

2021-04-12 22:05 UTC, kaiwalyajoshi commented on pages/dkp/kommander/1.3/include/kudo-intro.tmpl
> +- KUDO is built to support upgrades of services along with backup, recovery and the needs of observability.
Haha! You remind me of my Grade 12 English teacher! :)

2021-04-13 13:20 UTC, merged