Release Kaptain 1.2.0-1.1.0
mesosphere/dcos-docs-site pull request #3575
Opened 2021-04-30 05:10 UTC by akirillov

## Jira Ticket
[D2IQ-74822: site docs for the new Kaptain release](https://jira.d2iq.com/browse/D2IQ-74822)

## Description of changes being made
A new version of the site docs for Kaptain Release

## Checklist
- [x] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [x] Test all commands and procedures, if applicable.
- [x] Create your PR against `main`. 
- [x] Update all links if you are moving a page.
- [x] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-04-30 05:15 UTC, ianhellstrom commented on pages/dkp/kaptain/1.2.0-1.1.0/release-notes/1.1/index.md
> +* Upgradability and configuration updates of existing Kaptain installations without user workloads interruption
```suggestion
* Full zero-downtime upgradability of Kaptain and all of its configurations
```

2021-04-30 05:15 UTC, ianhellstrom commented on pages/dkp/kaptain/1.2.0-1.1.0/release-notes/1.1/index.md
> +* Upgradability and configuration updates of existing Kaptain installations without user workloads interruption
The top feature should be a bit punchier (as long as it's accurate).

2021-04-30 19:47 UTC, cmastr approved these changes

2021-04-30 19:53 UTC, cgawron1 approved these changes
lgtm

2021-04-30 22:38 UTC, cneth requested changes

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> + described above:
```suggestion
 To change the default MinIO cluster settings, create a configuration file `parameters.yaml` with the properties described above:
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +To learn more about MinIO distributed mode and replication see the [official documentation](https://docs.min.io/docs/).
```suggestion
This configuration will deploy 4 MinIO servers; each server will use 4 volumes with 10Gi capacity per volume.  
To learn more about MinIO distributed mode and replication see the [official documentation](https://docs.min.io/docs/).
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +## Expanding MinIO cluster
```suggestion
## Expanding the MinIO cluster
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +MinIO cluster can be expanded by increasing the number of server pools in the cluster.
```suggestion
The MinIO cluster can be expanded by increasing the number of server pools in the cluster. 
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +can only be scaled linearly, by using the initial server pool as a base scale unit.</p>
I find this wording confusing. How about this?

```suggestion
<p class="message--warning"><strong>WARNING: </strong>Expand an existing server pool is not supported. The cluster can only by adding additional server pools.</p>
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +This command will update the existing Kaptain instance and double up MinIO cluster capacity with almost no downtime.
Can we be more precise here about the downtime?  "Almost no downtime" doesn't sounds like "no downtime".  Should we add a note (like we have in the MySQL pages) about what can happen to clients during this change?

```suggestion
This command will update the existing Kaptain instance and double the MinIO cluster capacity with almost no downtime.  
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +replicated/rebalanced between the existing and the new pool.
```suggestion
1. Data redundancy is only guaranteed within a single server pool - if more than a half of the drives in a pool are lost, the data cannot be reconstructed.
2. When the MinIO cluster is expanded by adding a new server pool, the data from the initial pool will not be replicated/rebalanced between the existing and the new pool.
```

2021-04-30 22:38 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/troubleshooting/kaptain-1.1.0/index.md
> +excerpt: View troubleshooting information for Kaptain 1.1.0
This page is already 'versioned' higher up, do we need to include the version here as well?  It is confusing (and makes more work for us when releasing a new version) to have the version number in the title of the page here.

```suggestion
navigationTitle: Troubleshooting Kaptain
title: Troubleshooting Kaptain 
menuWeight: 10
excerpt: View troubleshooting information for Kaptain
```

2021-04-30 23:54 UTC, akirillov commented
thanks for the thorough review, @cneth! applied your suggestions.

2021-05-03 17:17 UTC, cneth requested changes
Looks good!  I found one minor issue in one of my previous suggestions.  I'll approve after that is applied!

2021-05-03 17:17 UTC, cneth commented on pages/dkp/kaptain/1.2.0-1.1.0/operations/minio/index.md
> +<p class="message--warning"><strong>WARNING: </strong>Expand an existing server pool is not supported. The cluster can only by adding additional server pools.</p>
Sorry, seems like there was some kind of typo in my previous comment! My apologies!

```suggestion
<p class="message--warning"><strong>WARNING: </strong>Expanding an existing server pool is not supported. The cluster can only by expanded by adding additional server pools.</p>
```

2021-05-03 18:37 UTC, cneth approved these changes

2021-05-05 13:42 UTC, merged