fix: add auto-ips ip range to no_proxy variable
mesosphere/dcos-docs-site pull request #3919
Opened 2021-11-29 14:30 UTC by vespian

## Description of changes being made
Add missing autoip ip range in NO_PROXY variable.

## Checklist
- [ ] Test all commands and procedures, if applicable.
- [ ] Create any new PRs against `production`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

2021-12-02 14:09 UTC, samvantran approved these changes

2021-12-03 22:39 UTC, vacas5 requested changes
I believe this change (for now at least) should be made in the konvoy 1.8 branch and then it will get autosync'd over to this repo

2021-12-05 20:11 UTC, vespian commented
> I believe this change (for now at least) should be made in the konvoy 1.8 branch and then it will get autosync'd over to this repo

I am sorry, but I am a bit lost with all these repos. I just want to add it to konvoy 1.x documentation.

@cmastr Can you help me out here please?

2021-12-06 22:31 UTC, vacas5 approved these changes

2021-12-06 22:31 UTC, merged