Qa/adding contributing style guides
mesosphere/dcos-docs-site pull request #3953
Opened 2021-12-13 23:00 UTC by msdolbey

## Jira Ticket

N/A

## Description of changes being made
Adding links to the style guides in the contributing doc.

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](./CONTRIBUTING.md) for more information.

2021-12-13 23:22 UTC, cmastr commented on CONTRIBUTING.md
> +In general, the documentation team follows the Microsoft Style Guide. Anything that deviates from that style guide is [documented here](https://wiki.d2iq.com/display/ENG/Documentation+Style+Guide).
Should we also reference Vale here?

2021-12-14 14:49 UTC, vacas5 commented on CONTRIBUTING.md
> +In general, the documentation team follows the Microsoft Style Guide. Anything that deviates from that style guide is [documented here](https://wiki.d2iq.com/display/ENG/Documentation+Style+Guide).
Also, I have issues with this link

2021-12-14 15:38 UTC, cmastr commented on CONTRIBUTING.md
> +In general, the documentation team follows the Microsoft Style Guide. Anything that deviates from that style guide is [documented here](https://wiki.d2iq.com/display/ENG/Documentation+Style+Guide).
```suggestion
In general, the documentation team uses Vale as our style guide. Anything that deviates from that style guide is decided by the docs team and implemented in Vale.
```

2021-12-14 15:40 UTC, cmastr approved these changes

2021-12-14 16:18 UTC, vacas5 approved these changes

2021-12-14 16:18 UTC, vacas5 requested changes
@msdolbey we might as well fix the Vale errors

2021-12-14 17:49 UTC, msdolbey commented on CONTRIBUTING.md
> +In general, the documentation team follows the Microsoft Style Guide. Anything that deviates from that style guide is [documented here](https://wiki.d2iq.com/display/ENG/Documentation+Style+Guide).
Added your comment @cmastr - more accurate, surely.

2021-12-14 17:50 UTC, msdolbey commented
> @msdolbey we might as well fix the Vale errors

@vacas5 - good call - done.

2021-12-14 22:21 UTC, cmastr commented on .github/styles/Vocab/Docs/accept.txt
> +hotfix
You can also do this like below (|es)

2021-12-14 22:24 UTC, msdolbey commented on .github/styles/Vocab/Docs/accept.txt
> +hotfixes
```suggestion
hotfix(|es)
```

2021-12-14 22:41 UTC, vacas5 approved these changes

2021-12-14 22:41 UTC, merged