docs: add example to OIDC page
mesosphere/dcos-docs-site pull request #3960
Opened 2021-12-15 15:13 UTC by makkes

Not having an example config mentioned here led to
https://jira.d2iq.com/browse/D2IQ-81508

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2021-12-15 15:32 UTC, makkes commented
See http://docs-d2iq-com-pr-3960.s3-website-us-west-2.amazonaws.com/ for a preview of the changed page.

2021-12-15 16:01 UTC, cmastr commented
Will need to front port to 2.2.

2021-12-16 15:01 UTC, Colin1841 approved these changes

2021-12-16 15:03 UTC, vacas5 requested changes
If you want to change 2.1 docs and have them show immediately on the production site, you'll need to merge into `main`

2021-12-16 15:12 UTC, vacas5 approved these changes

2021-12-16 15:16 UTC, merged