docs on gitea usage for catalog
mesosphere/dcos-docs-site pull request #4001
Opened 2021-12-28 19:54 UTC by takirala

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-82742

## Description of changes being made

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2021-12-28 19:58 UTC, vacas5 requested changes

2021-12-28 19:58 UTC, vacas5 commented on pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/index.md
> +<<<<<<< HEAD
looks like a conflict got leftover somehow

2021-12-29 15:18 UTC, vacas5 requested changes
looks like there are a lot of good vale recommendations for fixing the grammar

2021-12-29 15:18 UTC, vacas5 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +DKP supports using an external catalog git repository to install applications. In cases where an external repository is not accessible from within the cluster, you can use the Gitea server that comes
can you add Gitea to the vocab?

2021-12-29 15:18 UTC, vacas5 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +1. `git` needs to be installed in the local environment (from where a connection to air-gapped cluster can be established)
how about "install `git` in the local environment"?

2021-12-29 19:13 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +DKP supports using an external catalog git repository to install applications. In cases where an external repository is not accessible from within the cluster, you can use the Gitea server that comes
```suggestion
DKP supports using an external catalog git repository to install applications. In cases where an external repository is not accessible from within the cluster, to install applications, use the Gitea server that comes out-of-box with a Kommander deployment.
```

2021-12-29 19:13 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +1. Install `git` in the local environment (from where a connection to air-gapped cluster is established).
```suggestion
- Install `git` in the local environment (from where a connection to air-gapped cluster is established).

```

2021-12-29 19:14 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +1. Set the `VERSION` environment variable to the version of Kommander you want to install, for example:
```suggestion
To use the Gitea server that comes with a Kommander deployment, follow these steps:

1. Set the `VERSION` environment variable to the version of Kommander you want to install, for example:
```

2021-12-29 19:17 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
> +1. Once the newly created `GitRepository` on the management cluster is reconciled, corresponding `App`s are loaded by Kommander controller.
```suggestion
1. After the newly created `GitRepository` on the management cluster reconciles, any corresponding `App`s are loaded by Kommander controller.
```

2021-12-29 19:18 UTC, Colin1841 commented on pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
> +1.  If running in air-gapped environment, refer to [air-gapped setup instructions](../../../../../install/air-gapped/catalog).
```suggestion
1.  Refer to [air-gapped setup instructions](../../../../../install/air-gapped/catalog), if you are running in air-gapped environment.
```

2021-12-29 19:19 UTC, Colin1841 commented on pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/index.md
> +1. If running in air-gapped environment, refer to [air-gapped setup instructions](../../../../install/air-gapped/catalog).
```suggestion
1. Refer to [air-gapped setup instructions](../../../../install/air-gapped/catalog), if you are running in air-gapped environment.
```

2021-12-29 19:21 UTC, Colin1841 approved these changes

2021-12-29 19:45 UTC, takirala commented
@vacas5 can you PTAL

2021-12-29 19:54 UTC, vacas5 approved these changes
you didn't just make Vale happy, you made ME happy :)

2021-12-29 19:55 UTC, merged