docs: document new helm repository related k-cli commands
mesosphere/dcos-docs-site pull request #4052
Opened 2022-01-20 08:13 UTC by vespian

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-83457

## Description of changes being made
document new helm repository related k-cli commands

## Checklist
- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-01-20 14:53 UTC, cmastr commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Charts bundle is a Gziped Tar archive containing Helm charts required during Kommander installation.
Need to add this to accept.txt

2022-01-20 14:54 UTC, cmastr commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +In order to create bundle please execute command:
```suggestion
To create a bundle:
```

2022-01-20 14:54 UTC, cmastr commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +This will result in file `charts-bundle.tar.gz` being created.
```suggestion
Kommander creates `charts-bundle.tar.gz`.
```

2022-01-20 14:55 UTC, cmastr commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Optionally, the output file can be specified using `-o` parameter:
```suggestion
Optionally, specify the output using the `-o` parameter:
```

2022-01-20 14:55 UTC, cmastr commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Kommander charts bundle is uploaded to Kommander's internal Helm repository.
```suggestion
The Kommander charts bundle is uploaded to Kommander's internal Helm repository.
```

2022-01-20 16:02 UTC, cneth approved these changes

2022-01-20 16:02 UTC, cneth commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +It can be created using Kommander CLI or downloaded together with Kommander CLI
```suggestion
It can be created with the Kommander CLI or downloaded along with the Kommander CLI.
```

2022-01-20 16:02 UTC, cneth commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +It contents can be inspected using following command:
```suggestion
To inspect the contents:
```

2022-01-20 16:02 UTC, cneth commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Or upload new bundle altogether:
```suggestion
Or upload a new bundle:
```

2022-01-20 17:37 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +- A charts bundle file containing all the Helm charts that Kommander installation needs.
```suggestion
- A charts bundle file containing all Helm charts that Kommander installation needs.
```

2022-01-20 17:37 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Charts bundle is a Gziped Tar archive containing Helm charts required during Kommander installation.
```suggestion
The charts bundle is a Gziped Tar archive containing Helm charts, which are required during Kommander installation.
```

2022-01-20 17:40 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +Charts bundle is a Gziped Tar archive containing Helm charts required during Kommander installation.
Added to the list: (Gzipped|gzipped)

2022-01-20 17:43 UTC, Colin1841 commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +In order to create bundle please execute command:
```suggestion
Execute this command to create the charts bundle:
```

2022-01-20 17:52 UTC, Colin1841 approved these changes

2022-01-20 21:02 UTC, vacas5 requested changes
the source branch for this should be `main`

2022-01-20 22:24 UTC, cmastr commented
> the source branch for this should be `main`

@vacas5 and @vespian the JIRA for this seems to be a 2.2 change. So develop should be the correct branch, but this needs to be in the 2.2 folder. Am I interpreting that correctly?

2022-01-20 23:31 UTC, msdolbey commented on pages/dkp/kommander/2.1/install/air-gapped/index.md
> +It can be created using Kommander CLI or downloaded together with Kommander CLI
Create the charts bundle with the Kommander CLI or download along with the Kommander CLI.

2022-01-20 23:32 UTC, msdolbey commented
Yeah, this looks like it's just a file that needs to be adjusted (in the 2.2 folder)

2022-01-21 16:33 UTC, vespian commented
Thank you for thorough review and the fixes. I addressed all the comments and added some extra information wrt. installation. Please have another look.

2022-01-21 16:54 UTC, vacas5 approved these changes

2022-01-21 16:55 UTC, merged