adding backup and restore file on it's own
mesosphere/dcos-docs-site pull request #4110
Opened 2022-02-09 16:21 UTC by cmastr

Signed-off-by: Casie Oxford <coxford@d2iq.com>

NOTE: You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4068.s3-website-us-west-2.amazonaws.com/

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-78903 

## Description of changes being made

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-02-09 16:35 UTC, gflorinskaya commented
On the page http://docs-d2iq-com-pr-4110.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.1/backup-and-restore/
This link does not work "**Kommander stores all data as CRDs in the Kubernetes API and you can back up and restore it using the [standard Konvoy documentation]**(http://docs-d2iq-com-pr-4110.s3-website-us-west-2.amazonaws.com/dkp/konvoy/latest/backup/)."

2022-02-09 17:00 UTC, JohnB64-JBV requested changes

2022-02-11 22:34 UTC, cmastr commented on pages/dkp/kommander/2.1/backup-and-restore/index.md
> +For example, you can use the Velero command-line interface to back up or restore a cluster on demand, or to modify certain settings without changing the Velero configuration.
done

2022-02-11 22:35 UTC, cmastr commented on pages/dkp/kommander/2.1/backup-and-restore/index.md
> +In DKP, the Velero platform application is installed in the `kommander` namespace, instead of `velero`.  Thus, after installing the CLI, we recommend that you set the Velero CLI `namespace` config op
done

2022-02-11 22:39 UTC, JohnB64-JBV approved these changes

2022-02-11 22:40 UTC, cmastr commented
> On the page http://docs-d2iq-com-pr-4110.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.1/backup-and-restore/ This link does not work "**Kommander stores all data as CRDs in the Kubernetes API and you can back up and restore it using the [standard Konvoy documentation]**(http://docs-d2iq-com-pr-4110.s3-website-us-west-2.amazonaws.com/dkp/konvoy/latest/backup/)."

This is fixed. I just took out the link bc it's now this topic.

2022-02-11 22:41 UTC, cmastr commented on pages/dkp/kommander/2.1/backup-and-restore/index.md
> +You can also store your backups in Amazon S3 by configuring Velero in `cluster.yaml`  as follows:
take out?

2022-02-11 23:02 UTC, merged