docs: gatekeeper for 2.2
mesosphere/dcos-docs-site pull request #4112
Opened 2022-02-09 17:51 UTC by cwyl02

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-78966

## Description of changes being made

policy control / gatekeeper docs for 2.2

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-02-09 20:15 UTC, vacas5 approved these changes

2022-02-09 21:07 UTC, takirala approved these changes
cc @mikolajb can you glance over this just to make sure that the `3.7.0` bump doesnt change anything (i dont think it should, but just in case).

2022-02-09 21:07 UTC, takirala commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/privileged-containers/template.yaml
i dont like that we are using `../master/..` in the path as it is a moving depedency. looks like the repo does not have any tags so i guess this is fine.

2022-02-10 09:49 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Constraints are then used to inform Gatekeeper that the admin wants a ConstraintTemplate to be enforced, and how.
```suggestion
Constraints are then used to inform Gatekeeper that the admin wants to enforce a ConstraintTemplate, and how.
```

2022-02-10 09:51 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Constraints are then used to inform Gatekeeper that the admin wants a ConstraintTemplate to be enforced, and how.
```suggestion
Constraints are then used to inform Gatekeeper that the admin wants to enforce a ConstraintTemplate, and how.
```

2022-02-10 09:52 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Try to create a pod that mounts a disallowed host path by running the following command:
```suggestion
Create a pod that mounts a disallowed host path by running the following command:
```

2022-02-10 09:53 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Try to create a pod that mounts an allowed host path by running the following command:
```suggestion
Create a pod that mounts an allowed host path by running the following command:
```

2022-02-10 10:03 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +The Gatekeeper repository includes a [library of policies][gatekeeper-library] to replace Pod Security Policies which we will use in the following tutorials.
```suggestion
The Gatekeeper repository includes a [library of policies][gatekeeper-library] to replace Pod Security Policies which you will use in the following tutorials.
```

2022-02-10 10:06 UTC, gvasquezvargas reviewed
Just some comments on the language. Don't hesitate to provide feedback if needed! Thanks!

2022-02-10 19:27 UTC, cwyl02 commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Try to create a privileged pod by running the following command:
done

2022-02-10 19:27 UTC, cwyl02 commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Try to create a pod that mounts a disallowed host path by running the following command:
done

2022-02-10 19:27 UTC, cwyl02 commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +The Gatekeeper repository includes a [library of policies][gatekeeper-library] to replace Pod Security Policies which we will use in the following tutorials.
done

2022-02-10 19:27 UTC, cwyl02 commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +Try to create a pod that mounts an allowed host path by running the following command:
done

2022-02-11 15:04 UTC, JohnB64-JBV requested changes

2022-02-11 15:04 UTC, JohnB64-JBV commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +This tutorial describes how to use Gatekeeper to enforce policies by rejecting non-compliant resources. Specifically, this tutorial describes two constraints as a way to show how to use Gatekeeper as
```suggestion
This tutorial describes how to use Gatekeeper to enforce policies by rejecting non-compliant resources. Specifically, this tutorial describes two constraints as a way to use Gatekeeper as an alternative to [Pod Security Policies][psp]:
```

2022-02-11 15:04 UTC, JohnB64-JBV commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +- If you install Kommander with a custom configuration, make sure you enabled gatekeeper.
```suggestion
- If you install Kommander with a custom configuration, make sure you enabled Gatekeeper.
```

2022-02-11 15:04 UTC, JohnB64-JBV commented on pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md
> +#### Test that the constraint allows allowed host paths
```suggestion
#### Test that the constraint allows the allowed host paths
```

2022-02-11 16:58 UTC, JohnB64-JBV approved these changes

2022-02-11 16:58 UTC, merged