Add Applications, 2 sub-tasks here
mesosphere/dcos-docs-site pull request #4117
Opened 2022-02-11 15:29 UTC by Colin1841

2 Subtasks included here:
Copied Custom Applications: https://jira.d2iq.com/browse/D2IQ-84556
Added scope field: https://jira.d2iq.com/browse/D2IQ-84557

2022-02-11 19:13 UTC, gracedo commented on pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/application-metadata/index.md
> +| scope       |                      |                                                                                                 |
```suggestion
| scope       | workspace            | List of scopes, can be workspace and/or project currently.                                                                                               |
```

2022-02-11 19:16 UTC, gracedo commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
> +excerpt: Create a Git Repository in the Project namespace
```suggestion
excerpt: Create a Git Repository in the Workspace namespace
```

Please adapt all these pages to Workspace context

2022-02-11 22:26 UTC, cmastr approved these changes

2022-02-11 22:28 UTC, cmastr commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
> +menuWeight: 50
beta: true

2022-02-11 22:29 UTC, cmastr commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/git-repo-structure/index.md
> +title: Git repository structure
beta: true

2022-02-11 22:31 UTC, cmastr commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/index.md
> +title: Custom applications
beta: true

2022-02-11 23:02 UTC, cneth approved these changes

2022-02-14 21:28 UTC, cmastr approved these changes

2022-02-14 21:45 UTC, gracedo requested changes

2022-02-14 21:45 UTC, gracedo commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
> +excerpt: Create a Git Repository in the Project namespace
^^ bump on this - these pages were copied over from projects/, need to update all the project references to Workspace context

2022-02-15 18:59 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
> +menuWeight: 50
```suggestion
menuWeight: 50
beta: true
```

2022-02-15 18:59 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/git-repo-structure/index.md
> +title: Git repository structure
```suggestion
title: Git repository structure
beta: true
```

2022-02-15 19:18 UTC, Colin1841 commented
@gracedo - I applied a global term change, projects > workspace, and maintained the cases. However, I have a feeling this might have been a shotgun when a fly swatter was needed approach, so let me know if I need to back these out and do this manually!

2022-02-16 01:10 UTC, gracedo approved these changes
I don't think these pages should be labeled beta since these "features" are already out in 2.1.1

2022-02-16 13:55 UTC, Colin1841 commented on pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/application-metadata/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:25 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md
> +You can define how custom applications are displayed in the Kommander UI by defining a `metadata.yaml` file for each application in the git repository. You must define this file at `services/<applica
```suggestion
You can define how custom applications display in the Kommander UI by defining a `metadata.yaml` file for each application in the git repository. You must define this file at `services/<application>/metadata.yaml` for it to process correctly.
```

2022-02-16 14:26 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md
> +None of these fields are required for the application to be displayed in the UI.
```suggestion
None of these fields are required for the application to display in the UI.
```

2022-02-16 14:27 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:28 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:28 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:28 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/git-repo-structure/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:35 UTC, Colin1841 commented on pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/index.md
> +beta: true
```suggestion
beta: false
```

2022-02-16 14:52 UTC, cmastr commented on pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/application-metadata/index.md
> +beta: true
This is the 2.2 docs. DId we add these feature descriptions to 2.1 as well? @Colin1841 @gracedo

2022-02-16 16:47 UTC, Colin1841 commented
Duplicated Workspace Custom application pages to 2.1: 2.1/workspaces/applications/catalog-applications/custom-applications/

2022-02-16 16:59 UTC, merged