Qa/remove copy from shell code snippets
mesosphere/dcos-docs-site pull request #4152
Opened 2022-03-01 20:12 UTC by msdolbey

## Jira Ticket

## Description of changes being made

The gist is we can remove the copy icon from code snippets that are just responses/and shouldn't be copied.
SO, this will make it so that any code snippet fences that have `sh` will not show that copy icon.
BUT, so we still make sure that the copy is there for other types of code snippets, just reviewing all the pages that have code snippets and editing those that have `sh` for executable code snippets - and changing it so they are `bash` for the code snippet.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4152.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-03-02 00:23 UTC, vacas5 requested changes

2022-03-02 00:23 UTC, vacas5 commented on scss/components/_prism.scss
> +  z-index: 1000000;
`z-index: 10` has the same outcome. Also, a code comment as to why this is here would be really helpful.

2022-03-02 00:24 UTC, vacas5 submitted a review, later dismissed
@msdolbey I think we need to add something to the Contributing doc about this if we really want it to be a pattern

2022-03-18 13:16 UTC, cmastr commented
@msdolbey can you un-merge conflict this so we can merge it?

2022-03-18 21:17 UTC, cmastr approved these changes

2022-03-18 21:33 UTC, mwrightd2 approved these changes

2022-03-18 22:09 UTC, merged