[COPS-7154] 2.1.1 Air-Gapped Bundles v2
mesosphere/dcos-docs-site pull request #4220
Opened 2022-03-29 04:46 UTC by mwrightd2

## Jira Ticket

https://jira.d2iq.com/browse/COPS-7154

## Description of changes being made

Repurposed AWS Govcloud sections and added new material to it. Here's try #2!

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-03-30 21:45 UTC, cneth requested changes

2022-03-30 21:46 UTC, cmastr approved these changes

2022-03-31 17:28 UTC, dkoshkin commented
@mwrightd2 please take a look at the rendered pages and  http://docs-d2iq-com-pr-4220.s3-website-us-west-2.amazonaws.com/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/  (some already suggested by @cneth )

2022-03-31 18:11 UTC, mwrightd2 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +    ```
@cneth so if leaving this in here at all, just move to end of doc like a "hey if you want to do this, you can"

2022-04-05 20:02 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1.   To make the following examples easier to follow, set an environment variable with the cluster name.
```suggestion
1.  Set an environment variable with the cluster name. to make the following examples easier to follow.
```

2022-04-05 20:03 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1.   To make the following examples easier to follow, set an environment variable with the cluster name.
This had 3 spaces between 1.   and set - is that correct, or is single space, like the following steps below, correct?

2022-04-05 20:04 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1. Once the cluster has been created, Generate the cluster yaml.
```suggestion
1. Once the cluster is created, Generate the cluster yaml.
```

2022-04-05 20:04 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1.  Add the ClusterAPI controllers to the cluster
```suggestion
1.  Add the ClusterAPI controllers to the cluster.
```

2022-04-05 20:04 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1.  When the workload cluster is ready, move the cluster lifecycle services to the workload cluster.
```suggestion
1.  Move the cluster lifecycle services to the workload cluster, when the workload cluster is ready, 
```

2022-04-05 20:09 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/configurecluster/index.md
> +1.  Wait for the cluster control-plane to be ready
```suggestion
1.  Wait for the cluster control-plane to be ready.
```

2022-04-05 20:11 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/createami/index.md
> +Then, create your bootstrap cluster.
```suggestion
1.  Create your bootstrap cluster.
```

2022-04-05 20:13 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/index.md
> +DKP comes with an easy way to deploy in an air-gapped environment. Rather than one large package that includes the requirements for all air-gapped environments, D2iQ now provides air-gapped bundles f
Leave the D2i reference if you like it in here, nothing wrong with it, just looks a little clunky to me.

2022-04-05 20:14 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/loadbootstrap/index.md
> +## Setup docker
```suggestion
## Set up docker
```

2022-04-05 20:14 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/loadbootstrap/index.md
> +excerpt: Setup docker in your environment, configure your local registry, and load the bootstrap image.
```suggestion
excerpt: Set up docker in your environment, configure your local registry, and load the bootstrap image.
```

2022-04-05 20:15 UTC, Colin1841 commented on pages/dkp/konvoy/2.1/choose-infrastructure/airgapbundle/loadbootstrap/index.md
> +1. Once the registry has been seeded, load the bootstrap image.
```suggestion
1. Load the bootstrap image, after the registry is seeded.
```

2022-04-05 20:15 UTC, Colin1841 approved these changes

2022-04-06 00:18 UTC, mwrightd2 commented
Pulling down for: https://github.com/mesosphere/dcos-docs-site/pull/4270

2022-04-06 00:18 UTC, closed without merging