[Insights] Added the Tech preview information
mesosphere/dcos-docs-site pull request #4332
Opened 2022-04-11 18:49 UTC by Colin1841

## Jira Ticket 
https://jira.d2iq.com/browse/D2IQ-87587

## Description of changes being made
Added Technical Preview information.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

2022-04-11 18:51 UTC, Colin1841 commented on pages/dkp/kommander/2.2/insights/index.md
> +<p class="message--note"><strong>NOTE:</strong> We are offering DKP Insights with this release as a [Technical Preview](../legal/version-policy/#experimental-status) only.</p>
```suggestion
<p class="message--note"><strong>NOTE:</strong> We are offering DKP Insights with this release as a [Technical Preview](../legal/version-policy/#Technical-preview) only.</p>
```

2022-04-11 20:05 UTC, mmcelroy91 commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +Technical preview, or Tech Preview, is similar to Experimental status, but with the following differences:
```suggestion
Technical Preview, or Tech Preview, is similar to Experimental status, but with the following differences:
```

2022-04-11 20:06 UTC, mmcelroy91 commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +Technical preview, or Tech Preview, is similar to Experimental status, but with the following differences:
Not sure if Preview should be capitalized here and below as other references are on the page?  Not title, but other references.

2022-04-11 20:07 UTC, mmcelroy91 approved these changes

2022-04-12 16:18 UTC, nataliepina approved these changes
LGTM other than the comments to address

2022-04-12 19:20 UTC, cneth requested changes

2022-04-12 19:20 UTC, cneth commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +- The licensing is subject to change in future versions.
I don't think licensing should be mentioned in the support terms.  They have nothing to do with each other.

2022-04-12 19:20 UTC, cneth commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +- Tech Previews can be used in Production Environments.
I don't thing we want this here.     Keep in mind that the term 'tech preview' may apply to more than just insights over time.   And my understanding is that engineering is not agreeing to provide the current product (insights) with the SLA's necessary to support 'production environments'.   Certainly support is not.

2022-04-12 19:20 UTC, cneth commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +Technical Preview, or Tech Preview, is similar to Experimental status, but with the following differences:
I think it's exactly the same as Experimental, and we should either copy pasta that section here, or add the words technical preview to the 'Experimental' section header.

2022-04-12 20:10 UTC, Colin1841 commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +- Tech Previews can be used in Production Environments.
```suggestion
```

2022-04-12 20:12 UTC, Colin1841 commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +Technical Preview, or Tech Preview, is similar to Experimental status, but with the following differences:
```suggestion
Technical Preview, or Tech Preview, is similar to Experimental status, with the exception that Tech Preview items are considered part of the product and will be developed into future releases.
```

2022-04-12 20:12 UTC, kaiwalyajoshi commented
@Colin1841 since the licensing aspects aren't part of Support Policy, I guess there aren't that many differences between them.
We could merge both `Tech Preview` under `Experimental` or just duplicate the two sections with a few changes.

2022-04-12 20:13 UTC, Colin1841 commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +- The licensing is subject to change in future versions.
```suggestion
```

2022-04-13 20:48 UTC, kaiwalyajoshi approved these changes

2022-04-13 20:53 UTC, nataliepina commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +We provide Technical Preview, or Tech Preview, features to showcase capabilities that might be added to future versions of the product. As they are not yet production-ready, the support terms are the
```suggestion
We provide Technical Preview, or Tech Preview, features to showcase capabilities that might be added to future versions of the product. As they are not yet production-ready, the support terms are the same as defined for experimental features. Technical Preview features are not guaranteed to move forward, so could be removed from future versions of the product.

2022-04-13 20:53 UTC, nataliepina commented on pages/dkp/kommander/2.2/legal/version-policy/index.md
> +We provide Technical Preview, or Tech Preview, features to showcase capabilities that might be added to future versions of the product. As they are not yet production-ready, the support terms are the
There are some extra backticks here it seems

2022-04-13 20:58 UTC, cneth approved these changes
LGTM as long as you apply Natalie's comment about the superfluous backticks.

2022-04-13 21:27 UTC, merged