docs: fix spark workaround steps
mesosphere/dcos-docs-site pull request #4365
Opened 2022-04-19 18:56 UTC by cwyl02

## Description of changes being made
Add clarification about an assumption made in the command.

Also, fixed the command in the last step to delete pod -- now included a label filter in the command to correctly target spark operator. 

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-04-19 19:02 UTC, gracedo approved these changes

2022-04-19 19:43 UTC, cbuto approved these changes

2022-04-19 20:28 UTC, gracedo commented on pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
> +    # if your spark-operator appdeployment name doesn't contains spark, you need to adjust the grep command accordingly
```suggestion
    # if your spark-operator AppDeployment name doesn't contain "spark", you must adjust the grep command accordingly
```

2022-04-19 20:28 UTC, gracedo commented on pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
> +   # We always want to only deploy 1 spark operator per cluster
```suggestion
   # only one instance of spark operator should be deployed per cluster
```

2022-04-20 13:29 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
>  1. if you want to force a pod recreation, you can delete the old pod in `CrashLoopBackoff` by running
```suggestion
1. If you want to force a pod recreation, you can delete the old pod in `CrashLoopBackoff` by running:
```

2022-04-20 14:47 UTC, gvasquezvargas approved these changes

2022-04-20 16:40 UTC, msdolbey requested changes
The yaml file (so, this wasn't edited, but just caught it now) starting on line 180:
https://github.com/mesosphere/dcos-docs-site/pull/4365/files#diff-980fd7322ff40f75625bbf371d2a84d508611d1556bd2dbe176c48f15de13fa1R180
needs to be edited.

2022-04-20 16:46 UTC, msdolbey commented
I might be able to fix up that yaml - but I'd want to branch off of this just in case.

2022-04-20 18:41 UTC, msdolbey approved these changes
👍 
![nice fix](https://y.yarn.co/740bbebf-5942-4085-847a-90e319d0012e_text.gif)

2022-04-20 20:15 UTC, gflorinskaya approved these changes

2022-04-21 14:44 UTC, merged