Update index.md
mesosphere/dcos-docs-site pull request #4424
Opened 2022-04-29 19:40 UTC by mmcelroy91

https://jira.d2iq.com/browse/D2IQ-88839

###Description
If a user has previously upgraded from 1.8 to 2.1, an upgrade to 2.2 without the following instructions will break cert-manager.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-05-02 08:28 UTC, gvasquezvargas approved these changes
LGTM! But we need to copy this changes over to the kommander upgrade docs before merging. Ping me and we can do this together if you want to @mmcelroy91 💟

2022-05-02 13:58 UTC, mmcelroy91 commented
fixed in https://github.com/mesosphere/dcos-docs-site/pull/4425 so closing this one

2022-05-03 18:27 UTC, mmcelroy91 commented
Not a duplicate after we decided these steps for upgrading CAPI components were NOT a workaround for Release Notes, but rather a step needed in both Essential and Enterprise.  This is the Enterprise section.

2022-05-03 19:31 UTC, joejulian requested changes

2022-05-03 19:31 UTC, joejulian commented on pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
> +1.  If your cluster was upgraded to 2.1 from 1.8, prepare the old cert-manager installation for removal:
```suggestion
1.  If your cluster was upgraded to 2.1 from 1.8, prepare the old cert-manager installation for upgrade:
```

2022-05-03 19:31 UTC, joejulian commented on pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
> +1.  If your cluster was upgraded to 2.1 from 1.8, remove the old cert-manager you marked in step 1:
```suggestion
1.  If your cluster was upgraded to 2.1 from 1.8, remove the remaining old cert-manager resources from 1.8:
```

2022-05-03 20:05 UTC, joejulian approved these changes

2022-05-03 20:06 UTC, merged