Add minio attributions
mesosphere/dcos-docs-site pull request #4453
Opened 2022-05-13 02:03 UTC by kevinmiller-conley

## Jira Ticket

Urgent ask from legal and Tobi

## Description of changes being made

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-05-13 03:09 UTC, cneth approved these changes

2022-05-13 08:22 UTC, gvasquezvargas reviewed
Made tiny changes to make Vale happy. 
Do we have the same issues with MinIO in 2.3? If yes, we need to add to those pages as well.

2022-05-13 19:14 UTC, cmastr commented on pages/dkp/kommander/2.2/download/index.md
> +<p class="message--note"><strong>NOTE: </strong>This docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and con
We can't do this. @kevinmiller-conley was this explicitly called for?

2022-05-13 19:17 UTC, cmastr commented
Please pause until we can talk with outside council.

2022-05-13 19:18 UTC, cmastr requested changes
let's wait to talk to outside council.

2022-05-13 19:22 UTC, msdolbey commented on pages/dkp/kommander/2.2/download/index.md
> +<p class="message--note"><strong>NOTE: </strong>This docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and con
Docker is caps'ed

```suggestion
<p class="message--note"><strong>NOTE: </strong>This Docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and conditions of the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License 3.0</a>. For more information, refer to <a href="https://github.com/minio/minio">MinIO's source code</a>.</p>
```

2022-05-13 19:22 UTC, msdolbey commented on pages/dkp/kommander/2.2/install/air-gapped/index.md
> +<p class="message--note"><strong>NOTE: </strong>These docker images include code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and co
Docker is caps'ed

```suggestion
<p class="message--note"><strong>NOTE: </strong>These Docker images include code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and conditions of the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License 3.0</a>. For more information, refer to <a href="https://github.com/minio/minio">MinIO's source code</a>.</p>
```

2022-05-13 19:23 UTC, msdolbey commented on pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md
> +    <p class="message--note"><strong>NOTE: </strong>This docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and
Docker is caps'ed

```suggestion
    <p class="message--note"><strong>NOTE: </strong>This Docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and conditions of the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License 3.0</a>. For more information, refer to <a href="https://github.com/minio/minio">MinIO's source code</a>.</p>
```

2022-05-13 19:23 UTC, msdolbey commented on pages/dkp/konvoy/2.2/download/index.md
> +<p class="message--note"><strong>NOTE: </strong>This docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and con
Docker is caps'ed

```suggestion
<p class="message--note"><strong>NOTE: </strong>This Docker image includes code from the MinIO Project (“MinIO”), which is © 2015-2021 MinIO, Inc. MinIO is made available subject to the terms and conditions of the <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU Affero General Public License 3.0</a>. For more information, refer to <a href="https://github.com/minio/minio">MinIO's source code</a>.</p>
```

2022-05-17 15:47 UTC, cmastr approved these changes

2022-05-17 15:48 UTC, cmastr approved these changes

2022-05-17 15:57 UTC, merged