[Konvoy] Adding step to download containerd bundle for airgapped builds
mesosphere/dcos-docs-site pull request #4558
Opened 2022-06-28 14:29 UTC by mwrightd2

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-90568

## Description of changes being made

Added some steps to AMI creation.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-06-29 21:55 UTC, cmastr commented on pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +1. Download the the `containerd` bundle.
```suggestion
1. Download the `containerd` bundle.
```

2022-06-29 21:55 UTC, cmastr approved these changes

2022-07-07 14:26 UTC, cneth requested changes
AFAIK, similar steps will need to be added to other places as well, this is just for AWS, I believe that both vSphere and the preprovisioned airgapped (dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites-airgapped/) pages will need adjustments.

2022-07-07 14:26 UTC, cneth commented on pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +1. Set your `containerd` operating system:
```suggestion
1. Set a variable that indicates which os-specific `containerd` bundle to download:
2. ```

2022-07-07 14:26 UTC, cneth commented on pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +    <p class="message--note"><strong>NOTE: If you're installing on DKP v2.2.2 or above, you will need to continue onto step 7.</p>
This note is not needed on 2.3; this is just a part of the steps now.

```suggestion
```

2022-07-07 14:26 UTC, cneth commented on pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +1. Set your `containerd` operating system:
Please apply the same suggestions I made above to this page as well.

2022-07-08 17:13 UTC, mwrightd2 commented
@cneth I'm creating a separate PR for the other environments since this JIRA ticket is purely for AWS. Since that's the case would you be ok with approving?

2022-07-08 19:35 UTC, cneth commented on pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +2. ```
```suggestion
```

2022-07-08 19:36 UTC, cneth commented on pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +-   `ubuntu-18.04-x86_64`
```suggestion
    Note: available packages are:

    -   `centos-7.9-x86_64`
    -   `rhel-7.9-x86_64`
    -   `rhel-8.2-x86_64`
    -   `ubuntu-20.04-x86_64`
    -   `ubuntu-18.04-x86_64`
```

2022-07-08 19:45 UTC, cneth commented on pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
> +-   `ubuntu-18.04-x86_64`
```suggestion
    Available packages are:

    -   `centos-7.9-x86_64`
    -   `rhel-7.9-x86_64`
    -   `rhel-8.2-x86_64`
    -   `ubuntu-20.04-x86_64`
    -   `ubuntu-18.04-x86_64`
```

2022-07-08 19:55 UTC, cneth approved these changes

2022-07-08 20:07 UTC, merged