[DKP] Release Notes 2.2.2
mesosphere/dcos-docs-site pull request #4567
Opened 2022-07-07 07:15 UTC by mwrightd2

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-90183

## Description of changes being made

Release notes for DKP release 2.2.2.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-07-07 08:32 UTC, gvasquezvargas commented on pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
> +menuWeight: 20
So this file appears below 2.2.1 RN
```suggestion
menuWeight: 30
```

2022-07-07 08:37 UTC, gvasquezvargas commented on pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
> +### The Konvoy credentials plugin instructions embedded in the dex-k8s-authenticator dialogs don't work (COPS-7343)
```suggestion
### The Konvoy credentials plugin instructions embedded in the dex-k8s-authenticator dialogs do not work (COPS-7343)
```

2022-07-07 08:42 UTC, gvasquezvargas commented on pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
> +### Dex CRDS are out of date (COPS-7341)
```suggestion
### Outdated Dex CRDS (COPS-7341)
```

2022-07-07 08:45 UTC, gvasquezvargas commented on pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
> +### The Konvoy credentials plugin instructions embedded in the dex-k8s-authenticator containers do not work (COPS-7343)
```suggestion
### The Konvoy credentials plugin instructions embedded in the dex-k8s-authenticator containers did not work (COPS-7343)
```

2022-07-07 20:08 UTC, cneth requested changes
I reviewed the konvoy2 and kommander change logs, we're missing release notes for the following fixes.  I've drafted a proposed RN but these NEED TO BE REVIEWED BY ENGINEERING...  

---
https://jira.d2iq.com/browse/D2IQ-90140.  (Konvoy - CAPZ updated).

RN:   Updated Azure support to fix an issue with specifying Additional Tags (COPS-7346)

The Cluster API Azure (CAPZ) support was updated to resolve a race condition that could prevent the creation of additional resource tags.

---
https://jira.d2iq.com/browse/D2IQ-86169 

RN:   Updated Traefik Forward Auth to support 'clusterStorage' option. (COPS-7344)

The Traefik Forward Auth (TFA) component was updated to support storing of session cookies in-cluster instead of in the browser.

---
https://jira.d2iq.com/browse/D2IQ-84000

RN:  Added Continuous Deployment(CD)/Gitops to the View role

The CD/Gitops resource was added to the 'View' clusterRole, so that users with only this permission can view the CD/Gitops resources.

2022-07-07 21:07 UTC, cneth commented
Here's another one we found in our review:

https://jira.d2iq.com/browse/D2IQ-89452 (COPS-7336)

RN:   Kiali Platform Application not working properly (COPS-7336)

An installation problem that caused the Kiali platform application to malfunction has been corrected.

2022-07-07 21:26 UTC, cneth approved these changes

2022-07-08 00:42 UTC, cmastr commented on pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
> +| Cert Manager            | cert-manager                                   | 1.7.1   | - chart: 1.7.1<br>- cert-manager: 1.7.1
Did these get updates from Brian Mendoza jira?

2022-07-08 00:44 UTC, merged