[Kommander 2.2] Remove metal-lb from Kommander docs for 2.2+
mesosphere/dcos-docs-site pull request #4571
Opened 2022-07-08 17:11 UTC by mwrightd2

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-90790

## Description of changes being made

Removed instances of configuring MetalLB in Kommander 2.2 documentation.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-07-08 17:15 UTC, cmastr approved these changes

2022-07-08 21:07 UTC, cmastr commented
@mackdubya please add to Confluence as well.

2022-07-11 08:36 UTC, gvasquezvargas commented on pages/dkp/kommander/2.2/networking/load-balancing/index.md
> +For an on-premises deployment, Kommander utilizes MetalLB. MetalLB will now be installed when creating your Kubernetes cluster, refer to [the Konvoy installation instructions](.../konvoy/2.2/choose-i
```suggestion
For an on-premises deployment, Kommander utilizes MetalLB. MetalLB will now be installed when creating your Kubernetes cluster, refer to [the Konvoy installation instructions](../../../../konvoy/2.2/choose-infrastructure/pre-provisioned/metal-lb) for new clusters.
```

2022-07-11 12:23 UTC, gvasquezvargas commented
I tried to fix the links, but the preview is still showing me the last version with the "uncorrected" commands... 🤔

2022-07-12 19:22 UTC, cneth requested changes

2022-07-14 14:27 UTC, cmastr approved these changes

2022-07-14 14:31 UTC, cneth approved these changes

2022-07-14 14:35 UTC, merged