docs: updating 21 migragion steps
mesosphere/dcos-docs-site pull request #4669
Opened 2022-12-02 03:31 UTC by msdolbey

## Jira Ticket

[D2IQ-94600](https://d2iq.atlassian.net/browse/D2IQ-94600)

## Description of changes being made

There are some other edits, but the gist is in `pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md`

Where not everything was getting deployed correctly for migrated clusters re: gitea. This makes it work.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

2022-12-02 03:32 UTC, msdolbey commented
Also, @faiq - I added a bit about the KIB builder image if you want to double check me on that. But, I feel confident about it and used it myself.

2022-12-02 12:54 UTC, mmcelroy91 approved these changes

2022-12-02 14:51 UTC, cmastr approved these changes

2022-12-02 14:56 UTC, cmastr requested changes
Need to understand this requirement and maybe redocument as a work around before merging.

2022-12-02 15:05 UTC, cwyl02 approved these changes

2022-12-02 20:25 UTC, cwyl02 requested changes

2022-12-02 20:25 UTC, cwyl02 commented on pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
> +To do this, edit the Middleware object:
Maybe change this to modify `traefik-10.3.0-migration-overrides` configmap to make it a safer bet?

2022-12-05 13:40 UTC, mmcelroy91 approved these changes

2022-12-05 14:57 UTC, cwyl02 approved these changes

2022-12-05 19:07 UTC, msdolbey commented
> Need to understand this requirement and maybe redocument as a work around before merging.

I think we're good here after a code fix for 2.1.5 and above.

2022-12-05 19:14 UTC, msdolbey commented
Mary McElroy
[@dolbey]
 Casie is away today, so yes, I believe based on the over 100 message conversation that an agreeable resolution was achieved and we trust that you implemented it accordingly.  That’s a lot of fancy words to say, you can remove Do not merge!

2022-12-06 16:28 UTC, merged